### ISSUE TITLE
Minecraft Java Plugin Code

### ISSUE THREAD

**Issue by S42yt** [Root-Time/TogaBot#1]
time du hast eif plugin code auf java hier reingemacht namens test.jar 😭

**Comment by S42yt** [comment]
test.java nicht jar hahhaha

**Comment by Root-Time** [comment]
Ups xD

**Comment by S42yt** [comment]
ich schwör bin gerade schule aber wenn langweilig ist chille ich auf github 🔥

**Comment by S42yt** [comment]
@Root-Time fix du bitti 🙏
